package com.mbeddr.dsp.behavior;

/*Generated by MPS */

import com.mbeddr.core.expressions.behavior.UnaryExpression_BehaviorDescriptor;

public class SignalRange_BehaviorDescriptor extends UnaryExpression_BehaviorDescriptor {
  public SignalRange_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "com.mbeddr.dsp.structure.SignalRange";
  }
}
