package com.mbeddr.dsp.behavior;

/*Generated by MPS */

import com.mbeddr.core.expressions.behavior.Type_BehaviorDescriptor;

public class TimeDomainSignal_BehaviorDescriptor extends Type_BehaviorDescriptor {
  public TimeDomainSignal_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "com.mbeddr.dsp.structure.TimeDomainSignal";
  }
}
