package com.mbeddr.dataflow.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  private static String[] stringSwitchCases_846f5o_a0a0a = new String[]{"com.mbeddr.dataflow.structure.DataflowContext", "com.mbeddr.dataflow.structure.DataflowPin", "com.mbeddr.dataflow.structure.DataflowProcessor", "com.mbeddr.dataflow.structure.DataflowRouting"};

  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0a, fqName)) {
      case 0:
        return new DataflowContext_BehaviorDescriptor();
      case 1:
        return new DataflowPin_BehaviorDescriptor();
      case 3:
        return new DataflowRouting_BehaviorDescriptor();
      case 2:
        return new DataflowProcessor_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }
}
