package com.mbeddr.dataflow.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import com.mbeddr.ext.components.behavior.IComponentContent_BehaviorDescriptor;
import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;
import jetbrains.mps.smodel.SNode;
import com.mbeddr.core.base.behavior.IIdentifierNamedConcept_Behavior;
import com.mbeddr.ext.components.behavior.IComponentContent_Behavior;
import jetbrains.mps.lang.core.behavior.INamedConcept_Behavior;

public class DataflowPin_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IComponentContent_BehaviorDescriptor, INamedConcept_BehaviorDescriptor {
  public DataflowPin_BehaviorDescriptor() {
  }

  public String virtual_shortDescriptionForCCMenu_5470497459578304992(SNode thisNode) {
    return IIdentifierNamedConcept_Behavior.virtual_shortDescriptionForCCMenu_5470497459578304992(thisNode);
  }

  public String virtual_conceptLabel_5470497459580078362(SNode thisNode) {
    return IIdentifierNamedConcept_Behavior.virtual_conceptLabel_5470497459580078362(thisNode);
  }

  public String virtual_qualifiedName_5470497459578244269(SNode thisNode) {
    return IIdentifierNamedConcept_Behavior.virtual_qualifiedName_5470497459578244269(thisNode);
  }

  public String virtual_kindString_6641971848870642999(SNode thisNode) {
    return IComponentContent_Behavior.virtual_kindString_6641971848870642999(thisNode);
  }

  public String virtual_getFqName_1213877404258(SNode thisNode) {
    return INamedConcept_Behavior.virtual_getFqName_1213877404258(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "com.mbeddr.dataflow.structure.DataflowPin";
  }
}
