package com.mbeddr.dataflow.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;
import com.mbeddr.core.modules.behavior.IModuleContent_BehaviorDescriptor;
import jetbrains.mps.smodel.SNode;
import com.mbeddr.core.base.behavior.IIdentifierNamedConcept_Behavior;
import com.mbeddr.core.modules.behavior.IModuleContent_Behavior;
import jetbrains.mps.lang.core.behavior.INamedConcept_Behavior;

public class DataflowProcessor_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements INamedConcept_BehaviorDescriptor, IModuleContent_BehaviorDescriptor {
  public DataflowProcessor_BehaviorDescriptor() {
  }

  public String virtual_shortDescriptionForCCMenu_5470497459578304992(SNode thisNode) {
    return IIdentifierNamedConcept_Behavior.virtual_shortDescriptionForCCMenu_5470497459578304992(thisNode);
  }

  public SNode virtual_createImportedProxy_55677248263987031(SNode thisNode) {
    return IModuleContent_Behavior.virtual_createImportedProxy_55677248263987031(thisNode);
  }

  public String virtual_kindString_6641971848870642999(SNode thisNode) {
    return IModuleContent_Behavior.virtual_kindString_6641971848870642999(thisNode);
  }

  public boolean virtual_preventNameMangling_6708182213627106041(SNode thisNode) {
    return IModuleContent_Behavior.virtual_preventNameMangling_6708182213627106041(thisNode);
  }

  public Iterable<SNode> virtual_allReferencedModuleContents_1798411515023042202(SNode thisNode) {
    return IModuleContent_Behavior.virtual_allReferencedModuleContents_1798411515023042202(thisNode);
  }

  public String virtual_mangledName_1317894735999377422(SNode thisNode) {
    return IModuleContent_Behavior.virtual_mangledName_1317894735999377422(thisNode);
  }

  public boolean virtual_needsReferenceQualifier_1317894735999315639(SNode thisNode, SNode sourceModule) {
    return IModuleContent_Behavior.virtual_needsReferenceQualifier_1317894735999315639(thisNode, sourceModule);
  }

  public String virtual_conceptLabel_5470497459580078362(SNode thisNode) {
    return IIdentifierNamedConcept_Behavior.virtual_conceptLabel_5470497459580078362(thisNode);
  }

  public String virtual_referenceQualifier_1317894735999315602(SNode thisNode) {
    return IModuleContent_Behavior.virtual_referenceQualifier_1317894735999315602(thisNode);
  }

  public long virtual_sortWeight_7999989049973036118(SNode thisNode) {
    return IModuleContent_Behavior.virtual_sortWeight_7999989049973036118(thisNode);
  }

  public String virtual_qualifiedName_5470497459578244269(SNode thisNode) {
    return IIdentifierNamedConcept_Behavior.virtual_qualifiedName_5470497459578244269(thisNode);
  }

  public String virtual_getFqName_1213877404258(SNode thisNode) {
    return INamedConcept_Behavior.virtual_getFqName_1213877404258(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "com.mbeddr.dataflow.structure.DataflowProcessor";
  }
}
