package com.mbeddr.dataflow.behavior;

/*Generated by MPS */

import com.mbeddr.core.statements.behavior.Statement_BehaviorDescriptor;

public class DataflowRouting_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public DataflowRouting_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "com.mbeddr.dataflow.structure.DataflowRouting";
  }
}
