package com.mbeddr.dataflow.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum DataflowContextType {
  single_value("single-value", "single-value"),
  time_domain_signal("time-domain-signal", "time-domain-signal"),
  freq_domain_signal("freq-domain-signal", "freq-domain-signal");

  private String myName;
  private String myValue;

  DataflowContextType(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public String getValue() {
    return this.myValue;
  }

  public static List<DataflowContextType> getConstants() {
    List<DataflowContextType> list = ListSequence.fromList(new LinkedList<DataflowContextType>());
    ListSequence.fromList(list).addElement(DataflowContextType.single_value);
    ListSequence.fromList(list).addElement(DataflowContextType.time_domain_signal);
    ListSequence.fromList(list).addElement(DataflowContextType.freq_domain_signal);
    return list;
  }

  public static DataflowContextType getDefault() {
    return DataflowContextType.single_value;
  }

  public static DataflowContextType parseValue(String value) {
    if (value == null) {
      return DataflowContextType.getDefault();
    }
    if (value.equals(DataflowContextType.single_value.getValueAsString())) {
      return DataflowContextType.single_value;
    }
    if (value.equals(DataflowContextType.time_domain_signal.getValueAsString())) {
      return DataflowContextType.time_domain_signal;
    }
    if (value.equals(DataflowContextType.freq_domain_signal.getValueAsString())) {
      return DataflowContextType.freq_domain_signal;
    }
    return DataflowContextType.getDefault();
  }
}
