package com.mbeddr.dataflow.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Dataflow_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("60925c3a-d882-4765-88b2-8e6f4b319600(com.mbeddr.dataflow)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
