package com.mbeddr.dataflow.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum DataflowPinType {
  in("in", "in"),
  out("out", "out"),
  in_out("in/out", "in/out");

  private String myName;
  private String myValue;

  DataflowPinType(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public String getValue() {
    return this.myValue;
  }

  public static List<DataflowPinType> getConstants() {
    List<DataflowPinType> list = ListSequence.fromList(new LinkedList<DataflowPinType>());
    ListSequence.fromList(list).addElement(DataflowPinType.in);
    ListSequence.fromList(list).addElement(DataflowPinType.out);
    ListSequence.fromList(list).addElement(DataflowPinType.in_out);
    return list;
  }

  public static DataflowPinType getDefault() {
    return DataflowPinType.in;
  }

  public static DataflowPinType parseValue(String value) {
    if (value == null) {
      return DataflowPinType.getDefault();
    }
    if (value.equals(DataflowPinType.in.getValueAsString())) {
      return DataflowPinType.in;
    }
    if (value.equals(DataflowPinType.out.getValueAsString())) {
      return DataflowPinType.out;
    }
    if (value.equals(DataflowPinType.in_out.getValueAsString())) {
      return DataflowPinType.in_out;
    }
    return DataflowPinType.getDefault();
  }
}
