package com.mbeddr.dataflow.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum DataflowRoutingAction {
  connect("connect", "connect"),
  disconnect("disconnect", "disconnect"),
  reroute("reroute", "reroute");

  private String myName;
  private String myValue;

  DataflowRoutingAction(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public String getValue() {
    return this.myValue;
  }

  public static List<DataflowRoutingAction> getConstants() {
    List<DataflowRoutingAction> list = ListSequence.fromList(new LinkedList<DataflowRoutingAction>());
    ListSequence.fromList(list).addElement(DataflowRoutingAction.connect);
    ListSequence.fromList(list).addElement(DataflowRoutingAction.disconnect);
    ListSequence.fromList(list).addElement(DataflowRoutingAction.reroute);
    return list;
  }

  public static DataflowRoutingAction getDefault() {
    return DataflowRoutingAction.connect;
  }

  public static DataflowRoutingAction parseValue(String value) {
    if (value == null) {
      return DataflowRoutingAction.getDefault();
    }
    if (value.equals(DataflowRoutingAction.connect.getValueAsString())) {
      return DataflowRoutingAction.connect;
    }
    if (value.equals(DataflowRoutingAction.disconnect.getValueAsString())) {
      return DataflowRoutingAction.disconnect;
    }
    if (value.equals(DataflowRoutingAction.reroute.getValueAsString())) {
      return DataflowRoutingAction.reroute;
    }
    return DataflowRoutingAction.getDefault();
  }
}
