package com.mbeddr.dsp.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Dsp_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("21ac3db7-6546-45b7-90aa-f4db9c6cde07(com.mbeddr.dsp)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
