package com.mbeddr.dsp.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.impl.CompiledConceptDescriptor;
import jetbrains.mps.smodel.runtime.interpreted.StructureAspectInterpreted;

public class StructureAspectDescriptor implements jetbrains.mps.smodel.runtime.StructureAspectDescriptor {
  private static String[] stringSwitchCases_1htk8d_a0a0a = new String[]{"com.mbeddr.dsp.structure.SignalRange", "com.mbeddr.dsp.structure.TimeDomainSignal"};

  public StructureAspectDescriptor() {
  }

  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0a, conceptFqName)) {
      case 0:
        return new CompiledConceptDescriptor("com.mbeddr.dsp.structure.SignalRange", "com.mbeddr.core.expressions.structure.UnaryExpression", false, new String[]{"com.mbeddr.core.expressions.structure.UnaryExpression"}, new String[]{}, new String[]{});
      case 1:
        return new CompiledConceptDescriptor("com.mbeddr.dsp.structure.TimeDomainSignal", "com.mbeddr.core.expressions.structure.Type", false, new String[]{"com.mbeddr.core.expressions.structure.Type"}, new String[]{}, new String[]{});
      default:
        return StructureAspectInterpreted.getInstance().getDescriptor(conceptFqName);
    }
  }
}
